package Application.domain.models;

import Application.domain.enums.ReturnStatus;
import Application.domain.exceptions.InvalidRoleAssignmentException;
import Application.domain.exceptions.ReturnNotAllowedException;
import Application.domain.valueobjects.OrderStatus;
import Application.domain.valueobjects.SystemRole;

import java.time.LocalDateTime;

/**
 * Return
 *
 * Represents a buyer's request to return products from a delivered order.
 *
 * Business rule: a Return can only be requested against a delivered Order.
 */
public class Return {

    private final String returnId;
    private final Order order;
    private final Buyer buyer;
    private final String reason;
    private ReturnStatus returnStatus;
    private final LocalDateTime requestDate;
    private Refund refund;

    private Return(String returnId, Order order, Buyer buyer, String reason,
                   LocalDateTime requestDate) {
        if (returnId == null || returnId.isBlank()) {
            throw new IllegalArgumentException("Return id must not be null or blank");
        }
        if (order == null) {
            throw new IllegalArgumentException("A Return belongs to exactly one Order");
        }
        if (buyer == null) {
            throw new IllegalArgumentException("A Return is requested by one Buyer");
        }
        if (reason == null || reason.isBlank()) {
            throw new IllegalArgumentException("A Return requires the buyer's reason");
        }
        if (requestDate == null) {
            throw new IllegalArgumentException("Request date must not be null");
        }
        this.returnId = returnId;
        this.order = order;
        this.buyer = buyer;
        this.reason = reason;
        this.requestDate = requestDate;
        this.returnStatus = ReturnStatus.REQUESTED;
    }

    /**
     * Requests a return against an order. The order must be delivered and
     * belong to the requesting buyer.
     */
    public static Return request(Order order, Buyer buyer, String reason,
                                 String returnId, LocalDateTime requestDate) {
        if (!buyer.equals(order.getBuyer())) {
            throw new ReturnNotAllowedException(order.getOrderId(),
                    "only the buyer who placed the order may request a return");
        }
        if (order.getOrderStatus() != OrderStatus.DELIVERED) {
            throw new ReturnNotAllowedException(order.getOrderId(),
                    "returns can only be requested against delivered orders (current status: "
                            + order.getOrderStatus().getCode() + ")");
        }
        Return returnRequest = new Return(returnId, order, buyer, reason, requestDate);
        order.addReturn(returnRequest);
        return returnRequest;
    }

    public String getReturnId() { return returnId; }

    public Order getOrder() { return order; }

    public Buyer getBuyer() { return buyer; }

    public String getReason() { return reason; }

    public ReturnStatus getReturnStatus() { return returnStatus; }

    public LocalDateTime getRequestDate() { return requestDate; }

    public Refund getRefund() { return refund; }

    /** Approves the return. Only an Administrator may approve returns. */
    public void approve(Administrator approver) {
        requireStatus(ReturnStatus.REQUESTED, "approve");
        if (approver == null) {
            throw new InvalidRoleAssignmentException("approve a Return",
                    SystemRole.SUPERVISOR, SystemRole.ADMINISTRATOR);
        }
        this.returnStatus = ReturnStatus.APPROVED;
    }

    /** Rejects the return request. */
    public void reject() {
        requireStatus(ReturnStatus.REQUESTED, "reject");
        this.returnStatus = ReturnStatus.REJECTED;
    }

    /** Completes the return process (e.g. after stock reinstatement). */
    public void complete() {
        requireStatus(ReturnStatus.APPROVED, "complete");
        this.returnStatus = ReturnStatus.COMPLETED;
    }

    /** Links the refund generated by this return (only once). */
    public void attachRefund(Refund refund) {
        if (refund == null || !this.equals(refund.getRelatedReturn())) {
            throw new IllegalArgumentException("Refund must originate from this return");
        }
        if (this.refund != null) {
            throw new IllegalArgumentException("Return already generated a refund");
        }
        this.refund = refund;
    }

    private void requireStatus(ReturnStatus expected, String operation) {
        if (returnStatus != expected) {
            throw new IllegalArgumentException("Cannot " + operation + " return '" + returnId
                    + "': status is " + returnStatus + " (expected " + expected + ")");
        }
    }

    /**
     * Rebuilds a persisted return without re-applying request
     * validations. Used exclusively by persistence mappers.
     */
    public static Return reconstruct(String returnId, Order order, Buyer buyer, String reason,
                                     ReturnStatus returnStatus, LocalDateTime requestDate) {
        Return returnRequest = new Return(returnId, order, buyer, reason, requestDate);
        returnRequest.returnStatus = returnStatus;
        order.addReturn(returnRequest);
        return returnRequest;
    }
}
